### ISSUE TITLE
Allow to manually manage single users

### ISSUE THREAD

**Issue by gp42** [gp42/aws-auth-operator#3]
Current operator allows to synchronise IAM groups, but sometimes it is required to create a single user record which does not belong to IAM group.

For example, the following configuration:
```yaml
apiVersion: auth.ops42.org/v1alpha1
kind: AwsAuthSyncConfig
metadata:
  name: default
  namespace: kube-system
spec:
  mapUsers:
    - userarn: arn:aws:iam::677983237296:user/john
      username: john # optional, defaults to AWS username
      groups:
        - dev-operator-k8s-admins
        - dev-operator-k8s-users
```

Should result in the following AWS Auth configmap:
```yaml
...
  mapUsers: |
    - userarn: arn:aws:iam::677983237296:user/john
      username: john
      groups:
      - dev-operator-k8s-admins
      - dev-operator-k8s-users
```

This functionality should support combining with `syncIamGroups` configurations.
