### ISSUE TITLE
Support mapRoles configuration

### ISSUE THREAD

**Issue by gp42** [gp42/aws-auth-operator#4]
In order to fully manage `aws-auth` configMap, the operator needs to support role mapping.

Example configuration:
```yaml
  mapRoles: |
    - rolearn: <aws_role_arn>
      username: <username>  # optional, defaults to AWS Role name
      groups:
        - dev-operator-k8s-admins
        - dev-operator-k8s-users
```
